advanced_tab_locator = '//*[@data-cy="left-nav-item-Advanced"]'
general_information_locator = '//span[contains(text(),"General Information")]'

#Cpanel_email
button_email_account_locator = '//a[@id="item_email_accounts"]'
text_email_accounts_locator = '//span[text()="Email Accounts"]'
button_forwarders_locator = '//a[@id="item_forwarders"]'
text_forwarders_locator = '(//span[text()="Forwarders"])[2]'
button_email_routing_locator = '//a[@id="item_email_routing"]'
text_email_routing_locator  = '//span[text()="Forwarders"]'
button_autoresponder_locator = '//a[@id="item_autoresponders"]'
text_autoresponder_locator  = '//span[text()="Autoresponders"]'
button_item_mailing_lists_locator = '//a[@id="item_mailing_lists"]'
text_item_mailing_lists_locator = '//span[text()="Mailing Lists"]'
button_global_email_filter_locator = '//a[@id="item_global_email_filters"]'
text_global_email_filter_locator = '//span[text()="Global Email Filters"]'
button_email_filters_locator = '//a[@id="item_email_filters"]'
text_email_filters_locator = '(//span[text()="Email Filters"])[2]'
button_email_deliverbility_locator = '//a[@id="item_email_deliverability"]'
text_email_deliverbility_locator = '//span[text()="Email Deliverability"]'
button_spam_filters_locator = '//a[@id="item_apache_spam_assassin"]'
text_spam_filters_locator = '//span[text()="Spam Filters"]'
button_encryption_locator = '//a[@id="item_encryption"]'
text_encryption_locator = '//span[text()="Encryption"]'
button_box_trapper_locator = '//a[@id="item_boxtrapper"]'
text_box_trapper_locator = '//span[text()="BoxTrapper"]'
button_calenders_and_contacts_locator = '//a[@id="item_calendar_and_contacts"]'
text_calenders_and_contacts_locator = '//span[text()="Calendars and Contacts"]'
button_email_disk_usage_locator = '//a[@id="item_email_disk_usage"]'
text_email_disk_usage_locator = '//span[text()="Email Disk Usage"]'

#Cpanel_files
button_filemanager_locator = '//a[@id="item_file_manager"]'
text_filemanager_locator = '//span[contains(text()," File Manage")]'
button_images_locator = '//a[@id="item_images"]'
text_images_locator = '//span[text()="Images"]'
button_directory_privacy_locator = '//a[@id="item_directory_privacy"]'
text_directory_privacy_locator = '//span[text()="Directory Privacy"]'
button_disk_usage_locator = '//a[@id="item_disk_usage"]'
text_disk_usage_locator = '//span[text()="Disk Usage"]'
button_web_disk_locator = '//a[@id="item_web_disk"]'
text_web_disk_locator = '//span[text()="Web Disk"]'
button_ftp_accounts_locator = '//a[@id="item_ftp_accounts"]'
text_ftp_accounts_locator = '//span[text()="FTP Accounts"]'
button_ftp_connection_locator = '//a[@id="item_ftp_connections"]'
text_ftp_connection_locator = '//span[text()="FTP Connections"]'
button_ftp_anonymous_locator = '//a[@id="item_anonymous_ftp"]'
text_ftp_anonymous_locator = '//span[text()="Anonymous FTP"]'
button_git_versioncontrol_locator = '//a[@id="item_version_control"]'
text_git_versioncontrol_locator = '//span[text()="Git™ Version Control"]'

#Cpanel_database
button_my_sql_db_locator = '//a[@id="item_mysql_databases"]'
text_my_sql_db_locator = '//span[text()="MySQL® Databases"]'
button_my_sql_db_wizard_locator = '//a[@id="item_mysql_database_wizard"]'
text_my_sql_db_wizard_locator = '//span[text()="MySQL® Database Wizard"]'
button_mysql_wizard_locator = '//a[@id="item_remote_mysql"]'
text_mysql_wizard_locator = '//span[text()="Remote MySQL®"]'
button_postrage_sql_db_locator = '//a[@id="item_postgresql_databases"]'
text_postrage_sql_db_locator = '//span[text()="PostgreSQL Databases"]'
button_pl_sql_db_wizard_locator = '//a[@id="item_postgresql_database_wizard"]'
text_pl_sql_db_wizard_locator = '//span[text()="PostgreSQL Database Wizard"]'

#Cpanel_metrics
button_visitors_locator = '//a[@id="item_visitors"]'
text_visitors_locator = '//span[text()="Visitors"]'
button_errors_locator = '//a[@id="item_errors"]'
text_errors_locator = '//span[text()="Errors"]'
button_bandwidth_locator = '//a[@id="item_bandwidth"]'
text_bandwidth_locator = '//span[text()="Bandwidth"]'
button_rawaccess_locator = '//a[@id="item_raw_access"]'
text_rawaccess_locator = '//span[text()="Raw Access"]'
button_awstats_locator = '//a[@id="item_awstats"]'
text_awstats_locator = '//span[text()="Awstats"]'
button_weblizer_locator = '//a[@id="item_webalizer"]'
text_weblizer_locator = '//span[text()="Webalizer"]'
button_weblizerftp_locator = '//a[@id="item_webalizer_ftp"]'
text_weblizerftp_locator = '//span[text()="Webalizer FTP"]'
button_metricseditor_locator = '//a[@id="item_metrics_editor"]'
text_metricseditor_locator = '//span[text()="Metrics Editor"]'