lnk_mysites_locator = '//div[contains(text(),"My Sites")]'
txt_create_site_locator = '//button[contains(text(),"Create site")]'
txt_site_name_locator = '//input[@id="siteTitleInput"]'
btn_manage_sites_locator = '//button[contains(text(),"Manage Site")]'
tab_settings_locator = '//a[contains(text(),"Settings")]'
btn_delete_site_locator = '//button[@class="btn btn-danger btn-md right"]'
btn_delete_site_permanently_locator = '//button[@class="btn btn-danger ml2"]'
btn_create_new_site_locator = '//button[contains(text(),"Create New Site")]'
btn_create_site_next_locator = '//button[@class="btn btn-primary"]'
btn_choose_domain_next_locator = '//button[@class="btn btn-lg btn-primary"]'
txt_wp_installation_successfull_locator = '//h1[contains(text(),"Congratulations, WordPress installed successfully!")]'
lnk_go_back_to_mysites_locator = '//a[contains(text(),"Go back to My Sites")]'

txt_theme_overview_locator = '//span[contains(text(),"Themes")]'
txt_plugins_overview_locator = '//span[contains(text(),"Plugins")]'
txt_user_overview_locator = '//span[contains(text(),"User")]'
txt_updates_overview_locator = '//span[contains(text(),"Updates")]'
txt_uptodate_overview_locator = '//span[contains(text(),"Up to date")]'
btn_ctct_get_started_locator = '//a[@id="ctct-button"]'
txt_constant_contact_locator = '//h1[contains(text(),"Constant Contact")]'
tab_marketing_center_locator = '//a[contains(text(),"Marketing Center")]'
btn_google_ads_locator = '//button[contains(text(),"Get Started")]'
tab_users_locator = '//a[contains(text(),"Users")]'
btn_users_login_locator = '//a[@class="btn btn-default btn-sm"]'
tab_backups_locator = '//a[contains(text(),"Backups")]'
btn_add_codeguard_locator = '//button[contains(text(),"Add CodeGuard")]'
btn_billed_yearly_locator = '//label[contains(text(),"Billed yearly")]'

txt_basic_code_guard_locator = '//h3[contains(text(),"Basic")]'
txt_basic_code_guard_monthly_price_locator = '//span[contains(text(),"199")]'
txt_basic_code_guard_yearly_price_locator = '//span[contains(text(),"2028")]'
txt_professional_code_guard_locator = '//h3[contains(text(),"Professional")]'
txt_professional_code_guard_monthly_price_locator = '//span[contains(text(),"399")]'
txt_professional_code_guard_yearly_price_locator = '//span[contains(text(),"3588")]'
txt_premium_code_guard_locator = '//h3[contains(text(),"Premium")]'
txt_premium_code_guard_monthly_price_locator = '//span[contains(text(),"599")]'
txt_premium_code_guard_yearly_price_locator = '//span[contains(text(),"5988")]'
txt_enterprise_code_guard_locator = '//h3[contains(text(),"Enterprise")]'
txt_enterprise_code_guard_monthly_price_locator = '//span[contains(text(),"1499")]'
txt_enterprise_code_guard_yearly_price_locator = '//span[contains(text(),"14388")]'

tab_performance_locator = '//a[contains(text(),"Performance")]'
txt_performance_management_locator = '//h2[contains(text(),"Performance Management")]'
btn_cloudflare_cdn_locator = '//span[contains(text(),"Cloudflare")]'
txt_faster_load_times_locator = '//h3[contains(text(),"Get 2x faster load times, free.")]'
txt_cloudflare_cdn_locator = '//div[contains(text(),"Cloudflare CDN")]'

tab_plugins_locator = '//div[@id="main-content"]//div//div//div//div//div//a[contains(text(),"Plugins")]'
txt_your_plugins_locator = '//h2[contains(text(),"Your Plugins")]'
txt_akismet_anti_spam_locator = '//td[contains(text(),"Akismet Anti-Spam")]'

txt_site_url_locator = '//h2[contains(text(),"Site URL")]'
txt_automatic_updates_locator = '//h2[contains(text(),"Automatic Updates")]'
txt_content_revision_locator = '//h2[contains(text(),"Content")]'
txt_post_comments_locator = '//h2[contains(text(),"Comments")]'
txt_coming_soon_page_locator = '//h2[contains(text(),"Coming Soon Page")]'
txt_delete_site_locator = '//h2[contains(text(),"Delete Site")]'
txt_advanced_section_locator = '//h2[contains(text(),"Advanced")]'

tab_security_locator = '//a[contains(text(),"Security")]'
txt_security_certificate_locator = '//h2[contains(text(),"Security Certificate")]'
txt_file_integrity_check_locator = '//h2[contains(text(),"File Integrity Check")]'
txt_malware_security_locator = '//h2[contains(text(),"Malware Security")]'