## CPM
lnk_cpanel_manager_locator = '//a[contains(text(),"cPanel Manager")]'
btn_view_status_locator = '//input[@value="View Status"]'
btn_update_reset_locator = '(//input[@value="Update/Reset"])[1]'
txt_success_locator = '//h1[contains(text(),"Success")]'
txt_devs_locator = '//span[contains(text(),"Devs")]'
txt_db_query_locator = '//a[contains(text(),"DB Query")]'
txt_action_and_tools_locator = '//h1[contains(text(),"Actions/Tools")]'

### Service Monkey Locators ###
lnk_service_monkey_locator = '//a[contains(text(),"Service Monkey")]'
btn_cancel_full_refund_locator = '//button[text()="Submit"]'
btn_add_product_gotocart_locator = '//button[text()="Go To Cart"]'
iframe_cpanel_queue_cart_locator = '//iframe[@class="x-managed-iframe"]'
lbl_thank_you_for_purchase_locator = '//div[@class="heading-panel"]'
lnk_service_monkey_success_page_locator = '//a[contains(text(),"SM")]'
btn_service_monkey_cancel_locator = '(//div[contains(@class,"cancel")])[1]'
drpdwn_cancel_reason_locator = '//div[contains(text(),"internal - test account")]'
btn_service_monkey_submit_locator = '//button[contains(text(),"Submit")]'
drpdwn_cancel_reason_field_locator  = '//div[@class="x-window-bwrap"]//label[text()="Reason:"]//following-sibling::div//child::div[contains(@class,"form-field-wrap")]//img'
btn_continue_with_issue_credit_sm_locator = '//button[contains(text(),"Continue with Issue Credit")]'
btn_confirm_credit_locator = '//input[@value="Confirm Credit"]'
txt_account_deletion_success_locator = '//div[@id="content"]//h1[contains(text(),"Success")]'
txt_order_processed_locator = '//p[contains(text(), "Order processing could not be completed")]'
txt_domain_processing_locator = '//p[contains(text(), "Purchase Domain Name Registration")]'