# Locators

#login information
button_upsell_locator = '//span[text()="No thanks"]'
hosting_login_username_locator = '//input[@id="ldomain"]'
hosting_username_text_locator = '//label[text()="domain name"]'
hosting_login_password_locator = '//input[@id="lpass"]'
hosting_password_text_locator = '//label[text()="password"]'
hosting_login_submit_locator = '//button[contains(text(),"Log In")]'
domains_button_locator = '//div[text()="Domains"]'
sub_domains_button_locator = '//a[@data-cy="left-nav-subitem-Subdomains"]'
sub_domain_text_input_locator = '//input[@placeholder="Subdomain" and @id="input-text"]'
select_domain_dropdown_locator = '//div[@role="combobox" and @id="redirect-domain"]'
text_selc_locator = '//div[@class="selected item" and @role="option"]'
button_add_sub_domain_first_locator = '//button[text()="Add Subdomain"]'
button_add_sub_domain_second_locator = '//button[text()="Add subdomain"]'
button_remove_sub_domain_locator = '//button[text()="Remove"]'
button_delete_subdomain_locator = '//button[text()="Delete subdomain"]'
text_success_add_subdomain_locator = '//*[text()="Your subdomain is ready. Nice work!"]'
text_success_del_subdomain_locator = '//*[text()="test1234.test-permanent-account-sdet.com has been removed from your account."]'

#Account_center
button_upsell_locator = '//span[text()="No thanks"]'
text_avtar_initial_text_locator = '//a[@id="account-dropdown"]'
button_profile_locator = '//span[text()="Profile"]'
text_my_account_center_locator = '//h1[contains(text(),"My Account Center")]'
field_first_name_locator = '(//input[@id="firstName"])[2]'
field_last_name_locator = '(//input[@id="lastName"])[2]'
field_company_name_locator = '(//input[@id="company"])[2]'
field_street_address_locator = '(//input[@id="address"])[2]'
field_city_locator = '(//input[@id="city"])[2]'
list_state_locator = '(//div[text()="Maharashtra"])[2]'
list_state_select_locator = '(//span[text()="Maharashtra"])[2]'
list_country_locator = '(//div[text()="India"])[2]'
list_country_select_locator = '(//span[text()="India"])[2]'
field_zip_locator = '(//input[@id="zip"])[2]'
field_phone_locator = '(//input[@id="phone"])[2]'
field_email_locator = '(//input[@id="email"])[2]'
button_update_locator = '(//button[text()="Update"])[2]'
text_update_message_locator = '(//h3[text()="Contact information changed"])[1]'
tab_billing_locator = '//a[@id="billing-tab"]'
field_first_name_billing_locator = '//input[@id="firstName"]'
field_last_name_billing_locator = '//input[@id="lastName"]'
field_street_address_billing_locator = '//input[@id="address"]'
field_city_billing_locator = '//input[@id="city"]'
list_billing_state_locator = '(//div[text()="Maharashtra"])[1]'
list_billing_state_select_locator = '(//span[text()="Maharashtra"])[1]'
list_billing_country_locator = '(//div[text()="India"])[1]'
list_billing_country_select_locator = '(//span[text()="India"])[1]'
field_zip_billing_locator = '//input[@id="zip"]'
button_billing_update_locator = '//button[text()="Update"]'
text_success_billing_locator = '(//h3[text()="Billing Updated"])[1]'
tab_security_locator = '//a[@id="security-tab"]'
button_change_password_locator = '//button[text()="Change password"]'
text_main_password_locator = '//h3[text()="Main password"]'