## Account Center Info ##
account_center_text = 'My Account Center'
first_name = 'Test'
last_name = 'User'
company_name = 'Newfold Digital'
street_address = 'NESCO IT Park, Western Express Highway'
city = 'Mumbai'
zip_code = '400063'
phone_number = '18004194426'
email_address = 'test.user@newfold.com'
update_text = 'Contact information changed'
password_text = 'Main password'
state_text_variable = 'Maharashtra'
country_text_variable = 'India'