has_pro_service_endpoint = '/api/v1.0/users/has-pro-services'
pro_services_endpoint = '/api/v1.0/users/pro-services'
pro_services_cases_endpoint = '/api/v1.0/users/pro-services-cases'
pro_service_api_headers_xapi = 'yneujmorzfuezfwrczobxjr5jdg'
pro_service_api_headers_client = 'NSI'